// generated by Fast Light User Interface Designer (fluid) version 1.0009
/*
Revision 1 - Steve Lin, Jan. 14, 2002
Revision 2 - Alla and Kiran, Jan 18, 2002
Revision 3 - Jernej Barbic and Yili Zhao, Feb, 2012
*/

//#ifndef interface_h
//#define interface_h
//
//#include <FL/Fl.H>
//#include <FL/Fl_Window.H>
//#include <FL/Fl_Group.H>
//#include <FL/Fl_Button.H>
//#include <FL/Fl_Value_Input.H>
//#include <FL/Fl_Light_Button.H>
//#include <FL/Fl_Value_Slider.H>
//
//extern Fl_Window* main_window;
//
//extern Fl_Button* play_button;
//extern Fl_Button* pause_button;
//extern Fl_Button* reset_button;
//
//extern void play_callback(Fl_Button*, void*);
//
//extern void pause_callback(Fl_Button*, void*);
//
//extern void reset_callback(Fl_Button*, void*);
//
//Fl_Window* make_window();
//
//#endif
